# Generated by Django 6.0.5 on 2026-05-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('fresh_signs', models.TextField()),
                ('bad_signs', models.TextField()),
                ('pro_tip', models.TextField(blank=True, null=True)),
                ('best_season', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
